export { TabsRoot, TabsRoot as Tabs, type TabsRootProps, type TabsProps } from "./tabs-root"
export { TabsList, type TabsListProps } from "./tabs-list"
export { TabsItem, type TabsItemProps } from "./tabs-item"
export { TabsContent, type TabsContentProps } from "./tabs-content"
export { createTabs } from "./create-tabs"
