packages:
  - apps/*
  - packages/@fex-design/*
  - packages/@fex-design/components/*
  - packages/mock
  - configs/*
  - server
  - docs/site
  - docs/preview/*
  - docs/shared

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  msw: true
  unrs-resolver: true
  vue-demi: false

catalog:
  '@tailwindcss/postcss': 4.3.3
  '@tailwindcss/vite': 4.3.3
  tailwindcss: 4.3.3
  typescript: 6.0.3
  vite: 8.2.2

minimumReleaseAgeExclude:
  - oxfmt@0.67.0
  - prettier-plugin-svelte@4.1.1
  - prettier@3.9.6
  - svelte@5.56.4
  - vite@8.1.0
  - '@oxfmt/binding-android-arm-eabi@0.67.0'
  - '@oxfmt/binding-android-arm64@0.67.0'
  - '@oxfmt/binding-darwin-arm64@0.67.0'
  - '@oxfmt/binding-darwin-x64@0.67.0'
  - '@oxfmt/binding-freebsd-x64@0.67.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.67.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.67.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.67.0'
  - '@oxfmt/binding-linux-arm64-musl@0.67.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.67.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.67.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.67.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.67.0'
  - '@oxfmt/binding-linux-x64-gnu@0.67.0'
  - '@oxfmt/binding-linux-x64-musl@0.67.0'
  - '@oxfmt/binding-openharmony-arm64@0.67.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.67.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.67.0'
  - '@oxfmt/binding-win32-x64-msvc@0.67.0'
