packages:
  - apps/*
  - packages/@fex-design/*
  - packages/styles
  - packages/utils
  - packages/mock
  - configs/*
  - server
  - docs/site
  - docs/preview/*
  - docs/shared

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  msw: true
  unrs-resolver: true
  vue-demi: false

catalog:
  '@tailwindcss/postcss': 4.3.3
  '@tailwindcss/vite': 4.3.3
  tailwindcss: 4.3.3
  typescript: 6.0.3
  vite: 8.2.0

minimumReleaseAgeExclude:
  - svelte@5.56.4
  - vite@8.1.0
