export { default as DialogHeader } from './dialog-header.vue'
export { default as DialogBody } from './dialog-body.vue'
export { default as DialogFooter } from './dialog-footer.vue'
export { default as DialogTitle } from './dialog-title.vue'
export { default as DialogDescription } from './dialog-description.vue'
