export { default as ChevronLeftIcon } from './chevron-left-icon.vue'
export { default as ChevronRightIcon } from './chevron-right-icon.vue'
export { default as ChevronUpIcon } from './chevron-up-icon.vue'
export { default as ChevronDownIcon } from './chevron-down-icon.vue'
export { default as ChevronsRightIcon } from './chevrons-right-icon.vue'
export { default as ChevronsLeftIcon } from './chevrons-left-icon.vue'
