import type { AnchorClassNames, AnchorItem as AnchorItemData, AnchorStyles as AnchorStylesBase } from '@fex-design/core/anchor/types'
import { cn } from '@fex/utils'
import { For, Show, splitProps, type JSX } from 'solid-js'
import { AnchorIndicator, AnchorItem, AnchorLink, AnchorList, AnchorRail, AnchorRoot, type AnchorRootProps } from '../../primitive/anchor/anchor'
export type AnchorStyles = AnchorStylesBase<JSX.CSSProperties>
export interface AnchorProps extends Omit<AnchorRootProps, 'children'> { items: readonly AnchorItemData<JSX.Element>[]; classNames?: AnchorClassNames; styles?: AnchorStyles; onItemClick?: (event: MouseEvent, item: AnchorItemData<JSX.Element>) => void }
function AnchorItems(props: Pick<AnchorProps, 'items' | 'classNames' | 'styles' | 'onItemClick'>) { return <AnchorList class={props.classNames?.list} style={props.styles?.list}><For each={props.items}>{(item) => <AnchorItem value={item.key} target={item.target} {...(item.targetOffset === undefined ? {} : { targetOffset: item.targetOffset })} class={props.classNames?.item} style={props.styles?.item}><AnchorLink class={props.classNames?.link} style={props.styles?.link} onClick={(event) => props.onItemClick?.(event, item)}>{item.title}</AnchorLink><Show when={item.children?.length}>{item.children ? <AnchorItems items={item.children} classNames={props.classNames} styles={props.styles} onItemClick={props.onItemClick} /> : null}</Show></AnchorItem>}</For></AnchorList> }
export function Anchor(props: AnchorProps) { const [local, rest] = splitProps(props, ['items', 'classNames', 'styles', 'onItemClick', 'class', 'style']); return <AnchorRoot {...rest} class={cn(local.class, local.classNames?.root)} style={{ ...(typeof local.style === 'object' ? local.style : {}), ...local.styles?.root }}><AnchorRail class={local.classNames?.rail} style={local.styles?.rail}><AnchorIndicator class={local.classNames?.indicator} style={local.styles?.indicator} /></AnchorRail><AnchorItems items={local.items} classNames={local.classNames} styles={local.styles} onItemClick={local.onItemClick} /></AnchorRoot> }
export type { AnchorClassNames, AnchorItemData }
