export { SkeletonAvatar, type SkeletonAvatarProps } from './skeleton-avatar'
export { SkeletonBlock, type SkeletonBlockProps } from './skeleton-block'
export { SkeletonButton, type SkeletonButtonProps } from './skeleton-button'
export { SkeletonImage, type SkeletonImageProps } from './skeleton-image'
export { SkeletonInput, type SkeletonInputProps } from './skeleton-input'
export { SkeletonText, type SkeletonTextProps } from './skeleton-text'
