// Generated by scripts/generate-examples.mjs. Do not edit.
import type { Type } from '@angular/core'
import { AlertBasicExample as Example0 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/basic'
import { AlertCarouselExample as Example1 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/carousel'
import { AlertClosableExample as Example2 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/closable'
import { AlertCustomExample as Example3 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/custom'
import { AlertDirectionExample as Example4 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/direction'
import { AlertTypesExample as Example5 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/types'
import { AlertVariantsExample as Example6 } from '../../../../packages/@fex-design/components/angular/src/primitive/alert/examples/variants'
import { AnchorBasicExample as Example7 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/basic'
import { AnchorClickLockExample as Example8 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/click-lock'
import { AnchorControlledExample as Example9 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/controlled'
import { AnchorCustomClickExample as Example10 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/custom-click'
import { AnchorDirectionExample as Example11 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/direction'
import { AnchorHorizontalExample as Example12 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/horizontal'
import { AnchorOffsetExample as Example13 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/offset'
import { AnchorProgressExample as Example14 } from '../../../../packages/@fex-design/components/angular/src/primitive/anchor/examples/progress'
import { Landscape as Example15 } from '../../../../packages/@fex-design/components/angular/src/primitive/aspect-ratio/examples/landscape'
import { Portrait as Example16 } from '../../../../packages/@fex-design/components/angular/src/primitive/aspect-ratio/examples/portrait'
import { Square as Example17 } from '../../../../packages/@fex-design/components/angular/src/primitive/aspect-ratio/examples/square'
import { BadgeExample as Example18 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/badge'
import { BadgeWithIconExample as Example19 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/badge-with-icon'
import { BasicExample as Example20 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/basic'
import { CssVariablesExample as Example21 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/css-variables'
import { DirectionExample as Example22 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/direction'
import { GroupExample as Example23 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/group'
import { GroupCountExample as Example24 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/group-count'
import { GroupShapeExample as Example25 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/group-shape'
import { GroupWithIconExample as Example26 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/group-with-icon'
import { MaxCountExample as Example27 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/max-count'
import { ShapeExample as Example28 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/shape'
import { SizesExample as Example29 } from '../../../../packages/@fex-design/components/angular/src/primitive/avatar/examples/sizes'
import { BasicExample as Example30 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/basic'
import { Colors as Example31 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/colors'
import { CssVariables as Example32 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/css-variables'
import { Custom as Example33 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/custom'
import { Direction as Example34 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/direction'
import { Dot as Example35 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/dot'
import { Group as Example36 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/group'
import { Overflow as Example37 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/overflow'
import { Ribbon as Example38 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/ribbon'
import { Sizes as Example39 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/sizes'
import { Zero as Example40 } from '../../../../packages/@fex-design/components/angular/src/primitive/badge/examples/zero'
import { BasicExample as Example41 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/basic'
import { CombinationsExample as Example42 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/combinations'
import { CssVariablesExample as Example43 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/css-variables'
import { DirectionExample as Example44 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/direction'
import { EffectsExample as Example45 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/effects'
import { GroupExample as Example46 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/group'
import { IconsExample as Example47 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/icons'
import { LoadingExample as Example48 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/loading'
import { SizesExample as Example49 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/sizes'
import { StatesExample as Example50 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/states'
import { VariantsExample as Example51 } from '../../../../packages/@fex-design/components/angular/src/primitive/button/examples/variants'
import { BasicExample as Example52 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/basic'
import { CssVariablesExample as Example53 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/css-variables'
import { CustomHeaderExample as Example54 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/custom-header'
import { DirectionExample as Example55 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/direction'
import { ExtraExample as Example56 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/extra'
import { StylingExample as Example57 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/styling'
import { SurfaceExample as Example58 } from '../../../../packages/@fex-design/components/angular/src/primitive/card/examples/surface'
import { CheckboxPrimitiveBasicExample as Example59 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/basic'
import { CheckboxPrimitiveCheckAllExample as Example60 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/check-all'
import { CheckboxPrimitiveControlledExample as Example61 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/controlled'
import { CheckboxPrimitiveCssVariablesExample as Example62 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/css-variables'
import { CheckboxPrimitiveCustomIndicatorExample as Example63 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/custom-indicator'
import { CheckboxPrimitiveDirectionExample as Example64 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/direction'
import { CheckboxPrimitiveGroupExample as Example65 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/group'
import { CheckboxPrimitiveSizesExample as Example66 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/sizes'
import { CheckboxPrimitiveStatesExample as Example67 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/states'
import { CheckboxPrimitiveValidationExample as Example68 } from '../../../../packages/@fex-design/components/angular/src/primitive/checkbox/examples/validation'
import { BasicExample as Example69 } from '../../../../packages/@fex-design/components/angular/src/primitive/empty/examples/basic'
import { ContentExample as Example70 } from '../../../../packages/@fex-design/components/angular/src/primitive/empty/examples/content'
import { DirectionExample as Example71 } from '../../../../packages/@fex-design/components/angular/src/primitive/empty/examples/direction'
import { ImageExample as Example72 } from '../../../../packages/@fex-design/components/angular/src/primitive/empty/examples/image'
import { AffixesExample as Example73 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/affixes'
import { BasicExample as Example74 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/basic'
import { ConstraintsExample as Example75 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/constraints'
import { ControlsExample as Example76 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/controls'
import { CustomLogicExample as Example77 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/custom-logic'
import { EditingExample as Example78 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/editing'
import { FormatterExample as Example79 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/formatter'
import { KeyboardExample as Example80 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/keyboard'
import { RangeExample as Example81 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/range'
import { ValidationExample as Example82 } from '../../../../packages/@fex-design/components/angular/src/primitive/input-number/examples/validation'
import { AffixesExample as Example83 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/affixes'
import { BasicExample as Example84 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/basic'
import { ControlledExample as Example85 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/controlled'
import { FocusExample as Example86 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/focus'
import { GroupExample as Example87 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/group'
import { PasswordExample as Example88 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/password'
import { SearchExample as Example89 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/search'
import { SizesExample as Example90 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/sizes'
import { StatesExample as Example91 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/states'
import { ValidationExample as Example92 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/validation'
import { VariantsExample as Example93 } from '../../../../packages/@fex-design/components/angular/src/primitive/input/examples/variants'
import { Basic as Example94 } from '../../../../packages/@fex-design/components/angular/src/primitive/kbd/examples/basic'
import { ButtonExample as Example95 } from '../../../../packages/@fex-design/components/angular/src/primitive/kbd/examples/button'
import { DirectionExample as Example96 } from '../../../../packages/@fex-design/components/angular/src/primitive/kbd/examples/direction'
import { Group as Example97 } from '../../../../packages/@fex-design/components/angular/src/primitive/kbd/examples/group'
import { ArrowExample as Example98 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/arrow'
import { BasicExample as Example99 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/basic'
import { ContainerExample as Example100 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/container'
import { ControlledExample as Example101 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/controlled'
import { CustomLogicExample as Example102 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/custom-logic'
import { OffsetsExample as Example103 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/offsets'
import { PlacementExample as Example104 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/placement'
import { TriggersExample as Example105 } from '../../../../packages/@fex-design/components/angular/src/primitive/popover/examples/triggers'
import { RadioBasicExample as Example106 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/basic'
import { RadioButtonExample as Example107 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/button'
import { RadioControlledExample as Example108 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/controlled'
import { RadioCssVariablesExample as Example109 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/css-variables'
import { RadioDirectionExample as Example110 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/direction'
import { RadioSizesExample as Example111 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/sizes'
import { RadioStatesExample as Example112 } from '../../../../packages/@fex-design/components/angular/src/primitive/radio/examples/states'
import { SelectBasicExample as Example113 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/basic'
import { SelectClearExample as Example114 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/clear'
import { SelectControlledExample as Example115 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/controlled'
import { SelectVariablesExample as Example116 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/css-variables'
import { SelectCustomExample as Example117 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/custom-search'
import { SelectDirectionExample as Example118 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/direction'
import { SelectEmptyExample as Example119 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/empty-demo'
import { SelectFieldsExample as Example120 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/field-names'
import { SelectGroupExample as Example121 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/group'
import { SelectLocalExample as Example122 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/local-search'
import { SelectMultipleExample as Example123 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/multiple'
import { SelectPopupExample as Example124 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/popup-render-demo'
import { SelectAffixExample as Example125 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/prefix-suffix-demo'
import { SelectRemoteExample as Example126 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/remote-search'
import { SelectStylesExample as Example127 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/semantic-styles'
import { SelectSingleExample as Example128 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/single'
import { SelectVirtualExample as Example129 } from '../../../../packages/@fex-design/components/angular/src/primitive/select/examples/virtual'
import { Basic as Example130 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/basic'
import { Direction as Example131 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/direction'
import { List as Example132 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/list'
import { Menu as Example133 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/menu'
import { WithText as Example134 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/text'
import { Variants as Example135 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/variants'
import { Vertical as Example136 } from '../../../../packages/@fex-design/components/angular/src/primitive/separator/examples/vertical'
import { SkeletonAnimationExample as Example137 } from '../../../../packages/@fex-design/components/angular/src/primitive/skeleton/examples/animation'
import { SkeletonBasicExample as Example138 } from '../../../../packages/@fex-design/components/angular/src/primitive/skeleton/examples/basic'
import { SkeletonFormExample as Example139 } from '../../../../packages/@fex-design/components/angular/src/primitive/skeleton/examples/form'
import { SkeletonImageExample as Example140 } from '../../../../packages/@fex-design/components/angular/src/primitive/skeleton/examples/image'
import { SkeletonListExample as Example141 } from '../../../../packages/@fex-design/components/angular/src/primitive/skeleton/examples/list'
import { SkeletonTableExample as Example142 } from '../../../../packages/@fex-design/components/angular/src/primitive/skeleton/examples/table'
import { SliderBasicExample as Example143 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/basic'
import { SliderCssVariablesExample as Example144 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/css-variables'
import { SliderDirectionExample as Example145 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/direction'
import { SliderDisabledExample as Example146 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/disabled'
import { SliderDraggableRangeExample as Example147 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/draggable-range'
import { SliderEditableExample as Example148 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/editable'
import { SliderMarksExample as Example149 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/marks'
import { SliderRangeExample as Example150 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/range'
import { SliderSizesExample as Example151 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/sizes'
import { SliderWeightExample as Example152 } from '../../../../packages/@fex-design/components/angular/src/primitive/slider/examples/weight'
import { BasicExample as Example153 } from '../../../../packages/@fex-design/components/angular/src/primitive/spinner/examples/basic'
import { CustomIndicatorExample as Example154 } from '../../../../packages/@fex-design/components/angular/src/primitive/spinner/examples/custom-indicator'
import { OverlayExample as Example155 } from '../../../../packages/@fex-design/components/angular/src/primitive/spinner/examples/overlay'
import { SizesExample as Example156 } from '../../../../packages/@fex-design/components/angular/src/primitive/spinner/examples/sizes'
import { SwitchBasicExample as Example157 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/basic'
import { SwitchContentExample as Example158 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/content'
import { SwitchControlledExample as Example159 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/controlled'
import { SwitchCssVariablesExample as Example160 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/css-variables'
import { SwitchDirectionExample as Example161 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/direction'
import { SwitchDisabledExample as Example162 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/disabled'
import { SwitchLoadingExample as Example163 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/loading'
import { SwitchShapeExample as Example164 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/shape'
import { SwitchSizeExample as Example165 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/size'
import { SwitchValidationExample as Example166 } from '../../../../packages/@fex-design/components/angular/src/primitive/switch/examples/validation'
import { Basic as Example167 } from '../../../../packages/@fex-design/components/angular/src/primitive/tag/examples/basic'
import { Colors as Example168 } from '../../../../packages/@fex-design/components/angular/src/primitive/tag/examples/colors'
import { CssVariables as Example169 } from '../../../../packages/@fex-design/components/angular/src/primitive/tag/examples/css-variables'
import { DirectionExample as Example170 } from '../../../../packages/@fex-design/components/angular/src/primitive/tag/examples/direction'
import { Dynamic as Example171 } from '../../../../packages/@fex-design/components/angular/src/primitive/tag/examples/dynamic'
import { Variants as Example172 } from '../../../../packages/@fex-design/components/angular/src/primitive/tag/examples/variants'
import { BasicExample as Example173 } from '../../../../packages/@fex-design/components/angular/src/primitive/tooltip/examples/basic'
import { ColorExample as Example174 } from '../../../../packages/@fex-design/components/angular/src/primitive/tooltip/examples/color'
import { ControlledExample as Example175 } from '../../../../packages/@fex-design/components/angular/src/primitive/tooltip/examples/controlled'
import { CssVariablesExample as Example176 } from '../../../../packages/@fex-design/components/angular/src/primitive/tooltip/examples/css-variables'
import { DirectionExample as Example177 } from '../../../../packages/@fex-design/components/angular/src/primitive/tooltip/examples/direction'
import { PlacementExample as Example178 } from '../../../../packages/@fex-design/components/angular/src/primitive/tooltip/examples/placement'
import { AlertBasicExample as Example179 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/basic'
import { AlertCarouselExample as Example180 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/carousel'
import { AlertClosableExample as Example181 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/closable'
import { AlertCustomExample as Example182 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/custom'
import { AlertDirectionExample as Example183 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/direction'
import { AlertSemanticStylesExample as Example184 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/semantic-styles'
import { AlertTypesExample as Example185 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/types'
import { AlertVariantsExample as Example186 } from '../../../../packages/@fex-design/components/angular/src/ui/alert/examples/variants'
import { AnchorUiBasicExample as Example187 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/basic'
import { AnchorUiClickLockExample as Example188 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/click-lock'
import { AnchorUiControlledExample as Example189 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/controlled'
import { AnchorUiCustomClickExample as Example190 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/custom-click'
import { AnchorUiDirectionExample as Example191 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/direction'
import { AnchorUiHorizontalExample as Example192 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/horizontal'
import { AnchorUiOffsetExample as Example193 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/offset'
import { AnchorUiProgressExample as Example194 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/progress'
import { AnchorUiSemanticStylesExample as Example195 } from '../../../../packages/@fex-design/components/angular/src/ui/anchor/examples/semantic-styles'
import { Landscape as Example196 } from '../../../../packages/@fex-design/components/angular/src/ui/aspect-ratio/examples/landscape'
import { Portrait as Example197 } from '../../../../packages/@fex-design/components/angular/src/ui/aspect-ratio/examples/portrait'
import { Square as Example198 } from '../../../../packages/@fex-design/components/angular/src/ui/aspect-ratio/examples/square'
import { BasicExample as Example199 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/basic'
import { CssVariablesExample as Example200 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/css-variables'
import { DirectionExample as Example201 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/direction'
import { GroupExample as Example202 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/group'
import { GroupCountExample as Example203 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/group-count'
import { GroupShapeExample as Example204 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/group-shape'
import { GroupWithIconExample as Example205 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/group-with-icon'
import { MaxCountExample as Example206 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/max-count'
import { ShapeExample as Example207 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/shape'
import { SizesExample as Example208 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/sizes'
import { StylingExample as Example209 } from '../../../../packages/@fex-design/components/angular/src/ui/avatar/examples/styling'
import { Basic as Example210 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/basic'
import { Colors as Example211 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/colors'
import { CssVariables as Example212 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/css-variables'
import { Custom as Example213 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/custom'
import { Direction as Example214 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/direction'
import { Dot as Example215 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/dot'
import { Group as Example216 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/group'
import { Offset as Example217 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/offset'
import { Overflow as Example218 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/overflow'
import { Ribbon as Example219 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/ribbon'
import { Sizes as Example220 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/sizes'
import { Standalone as Example221 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/standalone'
import { Styling as Example222 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/styling'
import { Zero as Example223 } from '../../../../packages/@fex-design/components/angular/src/ui/badge/examples/zero'
import { BasicExample as Example224 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/basic'
import { CombinationsExample as Example225 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/combinations'
import { CssVariablesExample as Example226 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/css-variables'
import { DirectionExample as Example227 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/direction'
import { EffectsExample as Example228 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/effects'
import { GroupExample as Example229 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/group'
import { IconsExample as Example230 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/icons'
import { LoadingExample as Example231 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/loading'
import { SizesExample as Example232 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/sizes'
import { StatesExample as Example233 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/states'
import { VariantsExample as Example234 } from '../../../../packages/@fex-design/components/angular/src/ui/button/examples/variants'
import { BasicExample as Example235 } from '../../../../packages/@fex-design/components/angular/src/ui/card/examples/basic'
import { CssVariablesExample as Example236 } from '../../../../packages/@fex-design/components/angular/src/ui/card/examples/css-variables'
import { CustomHeaderExample as Example237 } from '../../../../packages/@fex-design/components/angular/src/ui/card/examples/custom-header'
import { DirectionExample as Example238 } from '../../../../packages/@fex-design/components/angular/src/ui/card/examples/direction'
import { ExtraExample as Example239 } from '../../../../packages/@fex-design/components/angular/src/ui/card/examples/extra'
import { StylingExample as Example240 } from '../../../../packages/@fex-design/components/angular/src/ui/card/examples/styling'
import { CheckboxUiBasicExample as Example241 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/basic'
import { CheckboxUiCheckAllExample as Example242 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/check-all'
import { CheckboxUiControlledExample as Example243 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/controlled'
import { CheckboxUiCssVariablesExample as Example244 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/css-variables'
import { CheckboxUiCustomIndicatorExample as Example245 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/custom-indicator'
import { CheckboxUiDirectionExample as Example246 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/direction'
import { CheckboxUiGroupExample as Example247 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/group'
import { CheckboxUiSemanticStylesExample as Example248 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/semantic-styles'
import { CheckboxUiSizesExample as Example249 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/sizes'
import { CheckboxUiStatesExample as Example250 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/states'
import { CheckboxUiValidationExample as Example251 } from '../../../../packages/@fex-design/components/angular/src/ui/checkbox/examples/validation'
import { BasicExample as Example252 } from '../../../../packages/@fex-design/components/angular/src/ui/empty/examples/basic'
import { ContentExample as Example253 } from '../../../../packages/@fex-design/components/angular/src/ui/empty/examples/content'
import { DirectionExample as Example254 } from '../../../../packages/@fex-design/components/angular/src/ui/empty/examples/direction'
import { ImageExample as Example255 } from '../../../../packages/@fex-design/components/angular/src/ui/empty/examples/image'
import { StylingExample as Example256 } from '../../../../packages/@fex-design/components/angular/src/ui/empty/examples/styling'
import { AffixesExample as Example257 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/affixes'
import { BasicExample as Example258 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/basic'
import { ConstraintsExample as Example259 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/constraints'
import { ControlsExample as Example260 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/controls'
import { CustomLogicExample as Example261 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/custom-logic'
import { EditingExample as Example262 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/editing'
import { FormatterExample as Example263 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/formatter'
import { KeyboardExample as Example264 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/keyboard'
import { RangeExample as Example265 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/range'
import { SemanticStylesExample as Example266 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/semantic-styles'
import { ValidationExample as Example267 } from '../../../../packages/@fex-design/components/angular/src/ui/input-number/examples/validation'
import { AffixesExample as Example268 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/affixes'
import { BasicExample as Example269 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/basic'
import { ControlledExample as Example270 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/controlled'
import { FocusExample as Example271 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/focus'
import { GroupExample as Example272 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/group'
import { PasswordExample as Example273 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/password'
import { SearchExample as Example274 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/search'
import { SemanticStylesExample as Example275 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/semantic-styles'
import { SizesExample as Example276 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/sizes'
import { StatesExample as Example277 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/states'
import { ValidationExample as Example278 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/validation'
import { VariantsExample as Example279 } from '../../../../packages/@fex-design/components/angular/src/ui/input/examples/variants'
import { Basic as Example280 } from '../../../../packages/@fex-design/components/angular/src/ui/kbd/examples/basic'
import { ButtonExample as Example281 } from '../../../../packages/@fex-design/components/angular/src/ui/kbd/examples/button'
import { DirectionExample as Example282 } from '../../../../packages/@fex-design/components/angular/src/ui/kbd/examples/direction'
import { Group as Example283 } from '../../../../packages/@fex-design/components/angular/src/ui/kbd/examples/group'
import { ArrowExample as Example284 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/arrow'
import { BasicExample as Example285 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/basic'
import { ContainerExample as Example286 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/container'
import { ControlledExample as Example287 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/controlled'
import { CustomLogicExample as Example288 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/custom-logic'
import { OffsetsExample as Example289 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/offsets'
import { PlacementExample as Example290 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/placement'
import { SemanticStylesExample as Example291 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/semantic-styles'
import { TriggersExample as Example292 } from '../../../../packages/@fex-design/components/angular/src/ui/popover/examples/triggers'
import { RadioBasicExample as Example293 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/basic'
import { RadioButtonExample as Example294 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/button'
import { RadioControlledExample as Example295 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/controlled'
import { RadioCssVariablesExample as Example296 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/css-variables'
import { RadioDirectionExample as Example297 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/direction'
import { RadioSemanticStylesExample as Example298 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/semantic-styles'
import { RadioSizesExample as Example299 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/sizes'
import { RadioStatesExample as Example300 } from '../../../../packages/@fex-design/components/angular/src/ui/radio/examples/states'
import { SelectBasicExample as Example301 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/basic'
import { SelectClearExample as Example302 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/clear'
import { SelectControlledExample as Example303 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/controlled'
import { SelectVariablesExample as Example304 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/css-variables'
import { SelectCustomSearchExample as Example305 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/custom-search'
import { SelectDirectionExample as Example306 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/direction'
import { SelectEmptyExample as Example307 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/empty-demo'
import { SelectFieldNamesExample as Example308 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/field-names'
import { SelectGroupExample as Example309 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/group'
import { SelectLocalSearchExample as Example310 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/local-search'
import { SelectMultipleExample as Example311 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/multiple'
import { SelectPopupExample as Example312 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/popup-render-demo'
import { SelectAffixExample as Example313 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/prefix-suffix-demo'
import { SelectRemoteSearchExample as Example314 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/remote-search'
import { SelectStylesExample as Example315 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/semantic-styles'
import { SelectSingleExample as Example316 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/single'
import { SelectVirtualExample as Example317 } from '../../../../packages/@fex-design/components/angular/src/ui/select/examples/virtual'
import { Basic as Example318 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/basic'
import { Direction as Example319 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/direction'
import { List as Example320 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/list'
import { Menu as Example321 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/menu'
import { WithText as Example322 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/text'
import { Variants as Example323 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/variants'
import { Vertical as Example324 } from '../../../../packages/@fex-design/components/angular/src/ui/separator/examples/vertical'
import { SkeletonAnimationExample as Example325 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/animation'
import { SkeletonBasicExample as Example326 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/basic'
import { SkeletonContentExample as Example327 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/content'
import { SkeletonFormExample as Example328 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/form'
import { SkeletonImageExample as Example329 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/image'
import { SkeletonListExample as Example330 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/list'
import { SkeletonStylesExample as Example331 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/styles'
import { SkeletonTableExample as Example332 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/table'
import { SkeletonWidthExample as Example333 } from '../../../../packages/@fex-design/components/angular/src/ui/skeleton/examples/width'
import { SliderBasicExample as Example334 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/basic'
import { SliderCssVariablesExample as Example335 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/css-variables'
import { SliderDirectionExample as Example336 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/direction'
import { SliderDisabledExample as Example337 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/disabled'
import { SliderDraggableRangeExample as Example338 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/draggable-range'
import { SliderEditableExample as Example339 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/editable'
import { SliderMarksExample as Example340 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/marks'
import { SliderRangeExample as Example341 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/range'
import { SliderSemanticStylesExample as Example342 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/semantic-styles'
import { SliderSizesExample as Example343 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/sizes'
import { SliderWeightExample as Example344 } from '../../../../packages/@fex-design/components/angular/src/ui/slider/examples/weight'
import { BasicExample as Example345 } from '../../../../packages/@fex-design/components/angular/src/ui/spinner/examples/basic'
import { CustomIndicatorExample as Example346 } from '../../../../packages/@fex-design/components/angular/src/ui/spinner/examples/custom-indicator'
import { OverlayExample as Example347 } from '../../../../packages/@fex-design/components/angular/src/ui/spinner/examples/overlay'
import { SizesExample as Example348 } from '../../../../packages/@fex-design/components/angular/src/ui/spinner/examples/sizes'
import { StylingExample as Example349 } from '../../../../packages/@fex-design/components/angular/src/ui/spinner/examples/styling'
import { SwitchBasicExample as Example350 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/basic'
import { SwitchContentExample as Example351 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/content'
import { SwitchControlledExample as Example352 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/controlled'
import { SwitchCssVariablesExample as Example353 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/css-variables'
import { SwitchDirectionExample as Example354 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/direction'
import { SwitchDisabledExample as Example355 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/disabled'
import { SwitchLoadingExample as Example356 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/loading'
import { SwitchSemanticStylesExample as Example357 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/semantic-styles'
import { SwitchShapeExample as Example358 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/shape'
import { SwitchSizeExample as Example359 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/size'
import { SwitchValidationExample as Example360 } from '../../../../packages/@fex-design/components/angular/src/ui/switch/examples/validation'
import { Basic as Example361 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/basic'
import { Colors as Example362 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/colors'
import { CssVariables as Example363 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/css-variables'
import { DirectionExample as Example364 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/direction'
import { Dynamic as Example365 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/dynamic'
import { SemanticStyles as Example366 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/semantic-styles'
import { Variants as Example367 } from '../../../../packages/@fex-design/components/angular/src/ui/tag/examples/variants'
import { BasicExample as Example368 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/basic'
import { ColorExample as Example369 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/color'
import { ControlledExample as Example370 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/controlled'
import { CssVariablesExample as Example371 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/css-variables'
import { DirectionExample as Example372 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/direction'
import { PlacementExample as Example373 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/placement'
import { SemanticStylesExample as Example374 } from '../../../../packages/@fex-design/components/angular/src/ui/tooltip/examples/semantic-styles'

export const examples: Record<string, Type<unknown>> = {
  'primitive/alert/basic': Example0,
  'primitive/alert/carousel': Example1,
  'primitive/alert/closable': Example2,
  'primitive/alert/custom': Example3,
  'primitive/alert/direction': Example4,
  'primitive/alert/types': Example5,
  'primitive/alert/variants': Example6,
  'primitive/anchor/basic': Example7,
  'primitive/anchor/click-lock': Example8,
  'primitive/anchor/controlled': Example9,
  'primitive/anchor/custom-click': Example10,
  'primitive/anchor/direction': Example11,
  'primitive/anchor/horizontal': Example12,
  'primitive/anchor/offset': Example13,
  'primitive/anchor/progress': Example14,
  'primitive/aspect-ratio/landscape': Example15,
  'primitive/aspect-ratio/portrait': Example16,
  'primitive/aspect-ratio/square': Example17,
  'primitive/avatar/badge': Example18,
  'primitive/avatar/badge-with-icon': Example19,
  'primitive/avatar/basic': Example20,
  'primitive/avatar/css-variables': Example21,
  'primitive/avatar/direction': Example22,
  'primitive/avatar/group': Example23,
  'primitive/avatar/group-count': Example24,
  'primitive/avatar/group-shape': Example25,
  'primitive/avatar/group-with-icon': Example26,
  'primitive/avatar/max-count': Example27,
  'primitive/avatar/shape': Example28,
  'primitive/avatar/sizes': Example29,
  'primitive/badge/basic': Example30,
  'primitive/badge/colors': Example31,
  'primitive/badge/css-variables': Example32,
  'primitive/badge/custom': Example33,
  'primitive/badge/direction': Example34,
  'primitive/badge/dot': Example35,
  'primitive/badge/group': Example36,
  'primitive/badge/overflow': Example37,
  'primitive/badge/ribbon': Example38,
  'primitive/badge/sizes': Example39,
  'primitive/badge/zero': Example40,
  'primitive/button/basic': Example41,
  'primitive/button/combinations': Example42,
  'primitive/button/css-variables': Example43,
  'primitive/button/direction': Example44,
  'primitive/button/effects': Example45,
  'primitive/button/group': Example46,
  'primitive/button/icons': Example47,
  'primitive/button/loading': Example48,
  'primitive/button/sizes': Example49,
  'primitive/button/states': Example50,
  'primitive/button/variants': Example51,
  'primitive/card/basic': Example52,
  'primitive/card/css-variables': Example53,
  'primitive/card/custom-header': Example54,
  'primitive/card/direction': Example55,
  'primitive/card/extra': Example56,
  'primitive/card/styling': Example57,
  'primitive/card/surface': Example58,
  'primitive/checkbox/basic': Example59,
  'primitive/checkbox/check-all': Example60,
  'primitive/checkbox/controlled': Example61,
  'primitive/checkbox/css-variables': Example62,
  'primitive/checkbox/custom-indicator': Example63,
  'primitive/checkbox/direction': Example64,
  'primitive/checkbox/group': Example65,
  'primitive/checkbox/sizes': Example66,
  'primitive/checkbox/states': Example67,
  'primitive/checkbox/validation': Example68,
  'primitive/empty/basic': Example69,
  'primitive/empty/content': Example70,
  'primitive/empty/direction': Example71,
  'primitive/empty/image': Example72,
  'primitive/input-number/affixes': Example73,
  'primitive/input-number/basic': Example74,
  'primitive/input-number/constraints': Example75,
  'primitive/input-number/controls': Example76,
  'primitive/input-number/custom-logic': Example77,
  'primitive/input-number/editing': Example78,
  'primitive/input-number/formatter': Example79,
  'primitive/input-number/keyboard': Example80,
  'primitive/input-number/range': Example81,
  'primitive/input-number/validation': Example82,
  'primitive/input/affixes': Example83,
  'primitive/input/basic': Example84,
  'primitive/input/controlled': Example85,
  'primitive/input/focus': Example86,
  'primitive/input/group': Example87,
  'primitive/input/password': Example88,
  'primitive/input/search': Example89,
  'primitive/input/sizes': Example90,
  'primitive/input/states': Example91,
  'primitive/input/validation': Example92,
  'primitive/input/variants': Example93,
  'primitive/kbd/basic': Example94,
  'primitive/kbd/button': Example95,
  'primitive/kbd/direction': Example96,
  'primitive/kbd/group': Example97,
  'primitive/popover/arrow': Example98,
  'primitive/popover/basic': Example99,
  'primitive/popover/container': Example100,
  'primitive/popover/controlled': Example101,
  'primitive/popover/custom-logic': Example102,
  'primitive/popover/offsets': Example103,
  'primitive/popover/placement': Example104,
  'primitive/popover/triggers': Example105,
  'primitive/radio/basic': Example106,
  'primitive/radio/button': Example107,
  'primitive/radio/controlled': Example108,
  'primitive/radio/css-variables': Example109,
  'primitive/radio/direction': Example110,
  'primitive/radio/sizes': Example111,
  'primitive/radio/states': Example112,
  'primitive/select/basic': Example113,
  'primitive/select/clear': Example114,
  'primitive/select/controlled': Example115,
  'primitive/select/css-variables': Example116,
  'primitive/select/custom-search': Example117,
  'primitive/select/direction': Example118,
  'primitive/select/empty-demo': Example119,
  'primitive/select/field-names': Example120,
  'primitive/select/group': Example121,
  'primitive/select/local-search': Example122,
  'primitive/select/multiple': Example123,
  'primitive/select/popup-render-demo': Example124,
  'primitive/select/prefix-suffix-demo': Example125,
  'primitive/select/remote-search': Example126,
  'primitive/select/semantic-styles': Example127,
  'primitive/select/single': Example128,
  'primitive/select/virtual': Example129,
  'primitive/separator/basic': Example130,
  'primitive/separator/direction': Example131,
  'primitive/separator/list': Example132,
  'primitive/separator/menu': Example133,
  'primitive/separator/text': Example134,
  'primitive/separator/variants': Example135,
  'primitive/separator/vertical': Example136,
  'primitive/skeleton/animation': Example137,
  'primitive/skeleton/basic': Example138,
  'primitive/skeleton/form': Example139,
  'primitive/skeleton/image': Example140,
  'primitive/skeleton/list': Example141,
  'primitive/skeleton/table': Example142,
  'primitive/slider/basic': Example143,
  'primitive/slider/css-variables': Example144,
  'primitive/slider/direction': Example145,
  'primitive/slider/disabled': Example146,
  'primitive/slider/draggable-range': Example147,
  'primitive/slider/editable': Example148,
  'primitive/slider/marks': Example149,
  'primitive/slider/range': Example150,
  'primitive/slider/sizes': Example151,
  'primitive/slider/weight': Example152,
  'primitive/spinner/basic': Example153,
  'primitive/spinner/custom-indicator': Example154,
  'primitive/spinner/overlay': Example155,
  'primitive/spinner/sizes': Example156,
  'primitive/switch/basic': Example157,
  'primitive/switch/content': Example158,
  'primitive/switch/controlled': Example159,
  'primitive/switch/css-variables': Example160,
  'primitive/switch/direction': Example161,
  'primitive/switch/disabled': Example162,
  'primitive/switch/loading': Example163,
  'primitive/switch/shape': Example164,
  'primitive/switch/size': Example165,
  'primitive/switch/validation': Example166,
  'primitive/tag/basic': Example167,
  'primitive/tag/colors': Example168,
  'primitive/tag/css-variables': Example169,
  'primitive/tag/direction': Example170,
  'primitive/tag/dynamic': Example171,
  'primitive/tag/variants': Example172,
  'primitive/tooltip/basic': Example173,
  'primitive/tooltip/color': Example174,
  'primitive/tooltip/controlled': Example175,
  'primitive/tooltip/css-variables': Example176,
  'primitive/tooltip/direction': Example177,
  'primitive/tooltip/placement': Example178,
  'ui/alert/basic': Example179,
  'ui/alert/carousel': Example180,
  'ui/alert/closable': Example181,
  'ui/alert/custom': Example182,
  'ui/alert/direction': Example183,
  'ui/alert/semantic-styles': Example184,
  'ui/alert/types': Example185,
  'ui/alert/variants': Example186,
  'ui/anchor/basic': Example187,
  'ui/anchor/click-lock': Example188,
  'ui/anchor/controlled': Example189,
  'ui/anchor/custom-click': Example190,
  'ui/anchor/direction': Example191,
  'ui/anchor/horizontal': Example192,
  'ui/anchor/offset': Example193,
  'ui/anchor/progress': Example194,
  'ui/anchor/semantic-styles': Example195,
  'ui/aspect-ratio/landscape': Example196,
  'ui/aspect-ratio/portrait': Example197,
  'ui/aspect-ratio/square': Example198,
  'ui/avatar/basic': Example199,
  'ui/avatar/css-variables': Example200,
  'ui/avatar/direction': Example201,
  'ui/avatar/group': Example202,
  'ui/avatar/group-count': Example203,
  'ui/avatar/group-shape': Example204,
  'ui/avatar/group-with-icon': Example205,
  'ui/avatar/max-count': Example206,
  'ui/avatar/shape': Example207,
  'ui/avatar/sizes': Example208,
  'ui/avatar/styling': Example209,
  'ui/badge/basic': Example210,
  'ui/badge/colors': Example211,
  'ui/badge/css-variables': Example212,
  'ui/badge/custom': Example213,
  'ui/badge/direction': Example214,
  'ui/badge/dot': Example215,
  'ui/badge/group': Example216,
  'ui/badge/offset': Example217,
  'ui/badge/overflow': Example218,
  'ui/badge/ribbon': Example219,
  'ui/badge/sizes': Example220,
  'ui/badge/standalone': Example221,
  'ui/badge/styling': Example222,
  'ui/badge/zero': Example223,
  'ui/button/basic': Example224,
  'ui/button/combinations': Example225,
  'ui/button/css-variables': Example226,
  'ui/button/direction': Example227,
  'ui/button/effects': Example228,
  'ui/button/group': Example229,
  'ui/button/icons': Example230,
  'ui/button/loading': Example231,
  'ui/button/sizes': Example232,
  'ui/button/states': Example233,
  'ui/button/variants': Example234,
  'ui/card/basic': Example235,
  'ui/card/css-variables': Example236,
  'ui/card/custom-header': Example237,
  'ui/card/direction': Example238,
  'ui/card/extra': Example239,
  'ui/card/styling': Example240,
  'ui/checkbox/basic': Example241,
  'ui/checkbox/check-all': Example242,
  'ui/checkbox/controlled': Example243,
  'ui/checkbox/css-variables': Example244,
  'ui/checkbox/custom-indicator': Example245,
  'ui/checkbox/direction': Example246,
  'ui/checkbox/group': Example247,
  'ui/checkbox/semantic-styles': Example248,
  'ui/checkbox/sizes': Example249,
  'ui/checkbox/states': Example250,
  'ui/checkbox/validation': Example251,
  'ui/empty/basic': Example252,
  'ui/empty/content': Example253,
  'ui/empty/direction': Example254,
  'ui/empty/image': Example255,
  'ui/empty/styling': Example256,
  'ui/input-number/affixes': Example257,
  'ui/input-number/basic': Example258,
  'ui/input-number/constraints': Example259,
  'ui/input-number/controls': Example260,
  'ui/input-number/custom-logic': Example261,
  'ui/input-number/editing': Example262,
  'ui/input-number/formatter': Example263,
  'ui/input-number/keyboard': Example264,
  'ui/input-number/range': Example265,
  'ui/input-number/semantic-styles': Example266,
  'ui/input-number/validation': Example267,
  'ui/input/affixes': Example268,
  'ui/input/basic': Example269,
  'ui/input/controlled': Example270,
  'ui/input/focus': Example271,
  'ui/input/group': Example272,
  'ui/input/password': Example273,
  'ui/input/search': Example274,
  'ui/input/semantic-styles': Example275,
  'ui/input/sizes': Example276,
  'ui/input/states': Example277,
  'ui/input/validation': Example278,
  'ui/input/variants': Example279,
  'ui/kbd/basic': Example280,
  'ui/kbd/button': Example281,
  'ui/kbd/direction': Example282,
  'ui/kbd/group': Example283,
  'ui/popover/arrow': Example284,
  'ui/popover/basic': Example285,
  'ui/popover/container': Example286,
  'ui/popover/controlled': Example287,
  'ui/popover/custom-logic': Example288,
  'ui/popover/offsets': Example289,
  'ui/popover/placement': Example290,
  'ui/popover/semantic-styles': Example291,
  'ui/popover/triggers': Example292,
  'ui/radio/basic': Example293,
  'ui/radio/button': Example294,
  'ui/radio/controlled': Example295,
  'ui/radio/css-variables': Example296,
  'ui/radio/direction': Example297,
  'ui/radio/semantic-styles': Example298,
  'ui/radio/sizes': Example299,
  'ui/radio/states': Example300,
  'ui/select/basic': Example301,
  'ui/select/clear': Example302,
  'ui/select/controlled': Example303,
  'ui/select/css-variables': Example304,
  'ui/select/custom-search': Example305,
  'ui/select/direction': Example306,
  'ui/select/empty-demo': Example307,
  'ui/select/field-names': Example308,
  'ui/select/group': Example309,
  'ui/select/local-search': Example310,
  'ui/select/multiple': Example311,
  'ui/select/popup-render-demo': Example312,
  'ui/select/prefix-suffix-demo': Example313,
  'ui/select/remote-search': Example314,
  'ui/select/semantic-styles': Example315,
  'ui/select/single': Example316,
  'ui/select/virtual': Example317,
  'ui/separator/basic': Example318,
  'ui/separator/direction': Example319,
  'ui/separator/list': Example320,
  'ui/separator/menu': Example321,
  'ui/separator/text': Example322,
  'ui/separator/variants': Example323,
  'ui/separator/vertical': Example324,
  'ui/skeleton/animation': Example325,
  'ui/skeleton/basic': Example326,
  'ui/skeleton/content': Example327,
  'ui/skeleton/form': Example328,
  'ui/skeleton/image': Example329,
  'ui/skeleton/list': Example330,
  'ui/skeleton/styles': Example331,
  'ui/skeleton/table': Example332,
  'ui/skeleton/width': Example333,
  'ui/slider/basic': Example334,
  'ui/slider/css-variables': Example335,
  'ui/slider/direction': Example336,
  'ui/slider/disabled': Example337,
  'ui/slider/draggable-range': Example338,
  'ui/slider/editable': Example339,
  'ui/slider/marks': Example340,
  'ui/slider/range': Example341,
  'ui/slider/semantic-styles': Example342,
  'ui/slider/sizes': Example343,
  'ui/slider/weight': Example344,
  'ui/spinner/basic': Example345,
  'ui/spinner/custom-indicator': Example346,
  'ui/spinner/overlay': Example347,
  'ui/spinner/sizes': Example348,
  'ui/spinner/styling': Example349,
  'ui/switch/basic': Example350,
  'ui/switch/content': Example351,
  'ui/switch/controlled': Example352,
  'ui/switch/css-variables': Example353,
  'ui/switch/direction': Example354,
  'ui/switch/disabled': Example355,
  'ui/switch/loading': Example356,
  'ui/switch/semantic-styles': Example357,
  'ui/switch/shape': Example358,
  'ui/switch/size': Example359,
  'ui/switch/validation': Example360,
  'ui/tag/basic': Example361,
  'ui/tag/colors': Example362,
  'ui/tag/css-variables': Example363,
  'ui/tag/direction': Example364,
  'ui/tag/dynamic': Example365,
  'ui/tag/semantic-styles': Example366,
  'ui/tag/variants': Example367,
  'ui/tooltip/basic': Example368,
  'ui/tooltip/color': Example369,
  'ui/tooltip/controlled': Example370,
  'ui/tooltip/css-variables': Example371,
  'ui/tooltip/direction': Example372,
  'ui/tooltip/placement': Example373,
  'ui/tooltip/semantic-styles': Example374,
}
