export const colorPickerAreaClassName = 'relative h-44 w-full touch-none overflow-hidden rounded-md [background:var(--color-picker-area-background)] outline-none select-none data-disabled:pointer-events-none data-disabled:opacity-50'
export const colorPickerAreaThumbClassName = 'pointer-events-none absolute size-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow-[0_0_0_1px_oklch(0_0_0/25%)]'
export const colorPickerChannelClassName = 'relative h-3 w-full touch-none rounded-full outline-none select-none data-[orientation=vertical]:h-44 data-[orientation=vertical]:w-3 data-disabled:pointer-events-none data-disabled:opacity-50'
export const colorPickerChannelTrackClassName = 'absolute inset-0 overflow-hidden rounded-[inherit] [background:var(--color-picker-channel-background)]'
export const colorPickerChannelThumbClassName = 'pointer-events-none absolute size-3 rounded-full border-2 border-white shadow-[0_0_0_1px_oklch(0_0_0/25%)]'
export const colorPickerSwatchClassName = 'relative inline-flex size-7 shrink-0 overflow-hidden rounded-md border border-border bg-[var(--color-picker-color,transparent)]'
export const colorPickerTransparencyGridClassName = 'absolute inset-0 -z-10 bg-[conic-gradient(oklch(0.86_0_0)_25%,white_0_50%,oklch(0.86_0_0)_0_75%,white_0)] bg-[length:8px_8px]'
export const colorPickerPanelClassName = 'grid w-64 gap-3 rounded-md border border-border bg-elevated-background p-3 text-elevated-foreground shadow-elevated'
export const gradientPickerTrackClassName = 'relative h-3 w-full cursor-crosshair rounded-full border border-border [background:var(--gradient-picker-background)]'
export const gradientPickerStopClassName = 'absolute top-1/2 size-3 -translate-x-1/2 -translate-y-1/2 cursor-grab rounded-full border-2 border-white bg-[var(--gradient-stop-color)] shadow-none data-selected:shadow-[0_0_0_2px_var(--gradient-stop-color)]'
