<script lang="ts">
  import { inputActionClassName,inputSearchAddonClassName } from '@fex-design/styles/input'
  import LoadingIcon from '@fex-design/svelte/icon/loading'
  import SearchIcon from '@fex-design/svelte/icon/search'
  import { Button } from '@fex-design/svelte/primitive/button'
  import { InputAddonAfter,InputAddonBefore,InputControl,InputGroup,InputPrefix,InputRoot } from '@fex-design/svelte/primitive/input'
  let result=$state('尚未搜索'); const search=(value:string,source:string)=>result=`${source}: ${value}`; const enter=(event:KeyboardEvent)=>{if(event.key==='Enter')search((event.currentTarget as HTMLInputElement).value,'enter')}
</script>
<div class="grid w-full gap-3"><InputGroup><InputRoot defaultValue="组件库"><InputControl onkeydown={enter}/></InputRoot><InputAddonAfter><Button variant="solid" color="primary" data-input-addon-fill="" aria-label="Search" class={inputSearchAddonClassName} onclick={()=>search('组件库','addonAfter')}><SearchIcon/></Button></InputAddonAfter></InputGroup><InputGroup><InputRoot defaultValue="加载中"><InputControl/></InputRoot><InputAddonAfter><Button variant="solid" color="primary" disabled data-input-addon-fill="" aria-label="Search" class={inputSearchAddonClassName}><LoadingIcon class="animate-spin"/></Button></InputAddonAfter></InputGroup><InputRoot><InputControl placeholder="仅按 Enter 搜索" onkeydown={enter}/></InputRoot><InputRoot><InputPrefix><button type="button" aria-label="Search" class={inputActionClassName} onclick={()=>search('','prefix')}><SearchIcon/></button></InputPrefix><InputControl placeholder="前置搜索图标" onkeydown={enter}/></InputRoot><InputGroup><InputAddonBefore><Button variant="solid" color="primary" data-input-addon-fill="" aria-label="Search" class={inputSearchAddonClassName} onclick={()=>search('','addonBefore')}>站内</Button></InputAddonBefore><InputRoot><InputControl placeholder="双侧搜索按钮" onkeydown={enter}/></InputRoot><InputAddonAfter><Button variant="solid" color="primary" data-input-addon-fill="" aria-label="Search" class={inputSearchAddonClassName} onclick={()=>search('','addonAfter')}>搜索</Button></InputAddonAfter></InputGroup><p class="text-sm text-muted-foreground">{result}</p></div>
