export { default as Tooltip } from './tooltip.svelte'
export { default as TooltipRoot } from './tooltip.svelte'
export { default as TooltipTrigger } from './tooltip-trigger.svelte'
export { default as TooltipPortal } from './tooltip-portal.svelte'
export { default as TooltipContent } from './tooltip-content.svelte'
export { default as TooltipArrow } from './tooltip-arrow.svelte'
export type { TooltipOptions as TooltipRootProps } from '@fex-design/core/tooltip/create-tooltip'
