export const progressExamples = {
  primitive: [
    { id: "basic", title: "基础用法", description: "基础条形进度条，支持顶部展示标签与百分比。" },
    { id: "circle", title: "环形进度", description: "360 度闭环环形进度条。" },
    { id: "status", title: "状态", description: "支持 pending、active、success、error 四种任务生命周期状态。" },
    { id: "color", title: "颜色", description: "支持自定义纯色、轨道底色与双色渐变。" },
    { id: "segmented", title: "分段进度", description: "线性与环形步进的分段进度。" },
    { id: "size", title: "尺寸", description: "支持不同尺寸与线条粗细。" },
    { id: "linecap", title: "端点形状", description: "支持 round, butt, square 端点风格。" },
    { id: "dashboard", title: "仪表盘", description: "仪表盘弧形进度条，支持自定义缺口角度与位置。" },
    { id: "dynamic", title: "动态进度", description: "外部动态控制进度值。" },
    { id: "direction", title: "RTL / LTR", description: "验证逻辑间距、标签和轨道在两种书写方向下的表现。" },
    { id: "custom-gap", title: "自定义分段间隔", description: "通过滑块调整环形步进段之间的间隔。" },
    { id: "format", title: "格式化与信息位置", description: "自定义数值格式，并对比顶部、右侧和底部信息位置。" },
    { id: "gradient", title: "渐变颜色", description: "在线性、圆环和仪表盘中展示渐变颜色。" },
  ],
  ui: [
    { id: "basic", title: "基础用法", description: "基础条形进度条，支持顶部展示标签与百分比。" },
    { id: "status", title: "状态", description: "支持 pending、active、success、error 四种任务生命周期状态。" },
    { id: "color", title: "颜色", description: "支持自定义纯色、轨道底色与双色渐变。" },
    { id: "segmented", title: "分段进度", description: "线性与环形步进的分段进度。" },
    { id: "size", title: "尺寸", description: "支持不同尺寸与线条粗细。" },
    { id: "linecap", title: "端点形状", description: "支持 round, butt, square 端点风格。" },
    { id: "circle", title: "环形进度", description: "360 度闭环环形进度条。" },
    { id: "dashboard", title: "仪表盘", description: "仪表盘弧形进度条，支持自定义缺口角度与位置。" },
    { id: "dynamic", title: "动态进度", description: "外部动态控制进度值。" },
    { id: "direction", title: "RTL / LTR", description: "验证逻辑间距、标签和轨道在两种书写方向下的表现。" },
    { id: "structured", title: "结构化样式", description: "通过 classNames 和 styles 分别定制根节点、轨道、填充条、标签和数值。" },
    { id: "custom-gap", title: "自定义分段间隔", description: "通过滑块调整环形步进段之间的间隔。" },
    { id: "format", title: "格式化与信息位置", description: "自定义数值格式，并对比顶部、右侧和底部信息位置。" },
    { id: "gradient", title: "渐变颜色", description: "在线性、圆环和仪表盘中展示渐变颜色。" },
  ],
} as const
