export const selectExamples = {
  primitive: [
    { id: 'basic', title: '基础组合', description: '组合 Root、Trigger、Content 与 Item。' },
    { id: 'single', title: '单选', description: '组合单选值与受控变化。' },
    { id: 'controlled', title: '受控与非受控', description: '对比 value 与 open 的受控状态和非受控初始值。' },
    { id: 'multiple', title: '多选', description: '组合多选值、标签和最大数量。' },
    { id: 'field-names', title: '字段映射', description: '把 profileId 映射为 value，把 displayName 映射为 label。' },
    { id: 'group', title: '分组', description: '组合 Group 与分组标题。', height: 400 },
    { id: 'local-search', title: '本地搜索', description: '通过 filterOption 过滤本地选项。' },
    { id: 'remote-search', title: '远程搜索', description: '模拟异步接口、加载状态与连续请求竞态处理。' },
    { id: 'custom-search', title: '自定义搜索', description: '使用字符顺序匹配；输入 rt 可以匹配 React。' },
    { id: 'clear', title: '清除', description: '组合可清除的 Trigger。' },
    { id: 'empty-demo', title: '空状态', description: '组合自定义空状态内容。' },
    { id: 'popup-render-demo', title: '自定义面板', description: '扩展 Content 面板内容。' },
    { id: 'prefix-suffix-demo', title: '前后缀', description: '组合 Trigger 输入前后缀。' },
    { id: 'direction', title: 'LTR 与 RTL', description: '对比中英文 LTR 与阿拉伯文 RTL 排列。' },
    { id: 'semantic-styles', title: '结构化样式', description: '按 Trigger、Value 和 Suffix 结构定制样式。' },
    { id: 'css-variables', title: 'CSS 变量', description: '通过输入类控件变量定制 Select。' },
    { id: 'virtual', title: '虚拟列表', description: '只渲染可视区与 overscan 项目。', height: 440 },
  ],
  ui: [
    { id: 'basic', title: '基础用法', description: '使用 options 快速生成单选。' },
    { id: 'single', title: '单选', description: '单选值与受控变化。' },
    { id: 'controlled', title: '受控与非受控', description: '对比 value 与 open 的受控状态和非受控初始值。' },
    { id: 'multiple', title: '多选', description: '多选值、标签和最大数量。' },
    { id: 'field-names', title: '字段映射', description: '把 profileId 映射为 value，把 displayName 映射为 label。' },
    { id: 'group', title: '分组', description: '使用分组和分组标题组织选项。', height: 400 },
    { id: 'local-search', title: '本地搜索', description: '在已有选项中进行搜索。' },
    { id: 'remote-search', title: '远程搜索', description: '模拟异步接口、加载状态与连续请求竞态处理。' },
    { id: 'custom-search', title: '自定义搜索', description: '使用字符顺序匹配；输入 rt 可以匹配 React。' },
    { id: 'clear', title: '清除', description: '复用 Input 的清除行为。' },
    { id: 'empty-demo', title: '空状态', description: '没有匹配选项时显示自定义内容。' },
    { id: 'popup-render-demo', title: '自定义面板', description: '扩展 Popover 面板内容。' },
    { id: 'prefix-suffix-demo', title: '前后缀', description: '通过 inputProps 自定义输入内容。' },
    { id: 'direction', title: 'LTR 与 RTL', description: '对比中英文 LTR 与阿拉伯文 RTL 排列。' },
    { id: 'semantic-styles', title: '结构化样式', description: '使用 classNames 与 styles 定制语义部位。' },
    { id: 'css-variables', title: 'CSS 变量', description: '通过输入类控件变量定制 Select。' },
    { id: 'virtual', title: '虚拟列表', description: 'UI 与 Primitive 使用同一虚拟化能力。', height: 440 },
  ],
} as const
